sampling_rate: 192000  # 44100
sampling_duration: 1.0

mel: {
       n_fft: 2560,
       hop_length: 470,
       n_mels: 128,
       mel_len: 450  # 1.1: 961, 1.0: 873, 0.5: 437
}

#sampling_rate = 44100
#hop_length = 345 * 2
#fmin = 20
#fmax = sampling_rate // 2
#n_mels = 128
#n_fft = n_mels * 20
#min_seconds = 0.5

data_path: "./input/train_data_nmel.p"
csv_path: "./input/training.csv"
wav_dir: "./input/training/"
max_val: 23.625134
min_val: -100.0

n_folds: 10
fold_seed: 42

channels: 1
num_epochs: 40
save_model: True
model_dir: "./model/"
experiment_name: ['origin_2ch', 'origin_1ch_9f', 'part_new_augs']
loader_params: {
  'batch_size': 16,
  'shuffle': 1,
  'num_workers': 4,
  'pin_memory': 0
}
#pretrained_path: './pretrained/mobilenetv3-small-55df8e1f.pth'
pretrained_path: './pretrained/mobilenetv3-large-1cd25616.pth'

lr: 0.0001
warmup_prop: 0.1
scheduler_params: {
  'first_cycle_steps': 20,
  'cycle_mult': 1.0,
  'max_lr': 6,    # THIS IS MULTIPLIER!!!
  'min_lr': 0.125,  # THIS IS MULTIPLIER!!!
  'warmup_steps': 5,
  'gamma': 0.9
}

model_params: {
  out_features_conv: 1000,
  out_features_dence: 9,
  mid_features: 500
}

ignore_files: [
  '00002.wav',
  '00044.wav',
  '00079.wav',
  '00172.wav',
  '00306.wav',
  '00396.wav',
  '00540.wav',
  '00629.wav',
  '00650.wav',
  '00723.wav',
  '01164.wav'
]