experiment_name: 'bootstrap'

# Paths
data_path: "/input/data.p"
csv_path: "/input/training.csv"
wav_dir: "/input/training/"
folds_path: "/input/folds.p"
weights_dir: "/weights/"
test_input_path: 'input_for_pred.csv'

# Audio params
sampling_rate: 192000
sampling_duration: 1.0
mel: {
       n_fft: 1764,
       hop_length: 220,
       n_mels: 64,
       mel_len: 961
}
max_val: 18.07428
min_val: -100.0

# Fold
fold_params: {
  n_splits: 10,
  shuffle: True,
  random_state: 1337
}

# Loader
loader_params: {
  'batch_size': 128,
  'shuffle': True,
  'num_workers': 4,
  'pin_memory': True
}

# Model
model_params: {
  out_features_conv: 1000,
  out_features_dense: 14,
  mid_features: 500,
  n_channels: 1,
  pretrained_path: '/pretrained/mobilenetv3-large-1cd25616.pth'
}

# Training
num_epochs: 150
save_model: True
patience: 40
bs_num: 150
warmup_prop: 0.1
lr: 0.0001
scheduler_params: {
  'first_cycle_steps': 150,
  'cycle_mult': 1.0,
  'max_lr': 0.001,
  'min_lr': 0.00001,
  'warmup_steps': 10,
}

# Predict test
test:
  model_names: ['bootstrap', 'bootstrap_2ch']
  average_weights: [1, 1]
  n_feats: [14, 14]
  n_channels: [1, 2]
  device: 'cpu'

# Bad files
ignore_files: [
  '00002.wav',
  '00044.wav',
  '00079.wav',
  '00172.wav',
  '00306.wav',
  '00396.wav',
  '00540.wav',
  '00629.wav',
  '00650.wav',
  '00723.wav',
  '01164.wav'
]